name: Deploy
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "book.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: main
      - name: Build
        uses: ./.github/actions/build
